name: 09 - Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing Step
        # exit with a non-zero code to simulate a failure
        run: |
          exit 1
      - name: I will be skipped
        run: echo "I will print if previous steps succeed"
      - name: I will execute
        #should be executed only if any of the previous steps have failed
        if: ${{ failure() }}
        run: echo "I will print if any of the previous steps have failed"
      - name: I will execute
        #should be executed only if the workflow has not been cancelled
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled"
      - name: I will execute when cancelled
        #should be executed only if the workflow has been cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow is cancelled"
